version: '2'

volumes:
  nextcloud:
  db_data:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nextcloud

  app:
    image: nextcloud
    ports:
      - 8003:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always